name: Daily update check

on: 
  #workflow_dispatch
  schedule:
    - cron:  '30 00 * * *'

permissions:
  contents: write

env:
  CATALOG_URL: https://messervices.cyber.gouv.fr/visas/catalogue-produits-services-profils-de-protection-sites-certifies-qualifies-agrees-anssi.pdf
  CATALOG_FNAME: /tmp/catalogue.pdf
  CATALOG_HASH_FNAME: /tmp/catalogue.sha256
  LASTEST_HASH_FNAME: latest_file_sha256.txt
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install prerequisites
      run: |
        pip install curl_cffi

    - name: Get file
      run: |
        cd /tmp/
        curl-cffi get --headers "$CATALOG_URL" -d -o "$CATALOG_FNAME"
        ls -alh "$CATALOG_FNAME"

    - name: Check
      run: |
        cd /tmp/
        sha256sum "$CATALOG_FNAME" > "$CATALOG_HASH_FNAME"

        if sha256sum -c "$GITHUB_WORKSPACE/$LASTEST_HASH_FNAME"; then
          echo "[+] NO UPDATE"
        else
          echo "[!] FILE UPDATE"
          CURRENT_YEAR_DIR=$(date '+%Y')
          CURRENT_DATE=$(date '+%Y%m%d')
          
          cd "$GITHUB_WORKSPACE"
          mkdir -p "$CURRENT_YEAR_DIR"
          cp -f "$CATALOG_FNAME" "$CURRENT_YEAR_DIR/$CURRENT_DATE-catalogue.pdf"
          cp -f "$CATALOG_HASH_FNAME" "$GITHUB_WORKSPACE/$LASTEST_HASH_FNAME"
          
          git config user.name scraping-bot
          git config user.email github-actions@github.com
          git add -A
          git commit -m "updating bot - $(date '+%Y/%m/%d')"
          git push
        fi
